[package]
name = "rust-runner"
version = "0.1.0"
authors = ["NikVolf <nikvolf@gmail.com>"]

[dependencies]
parity-wasm = { git="https://github.com/nikvolf/parity-wasm" }
wasm-utils = { git="https://github.com/paritytech/wasm-utils" }